services:
  shiny-server:
    image: rocker/shiny-verse:4.6.1
    container_name: shiny-server
    ports:
      - 3939:3838
    environment:
      - R_LIBS=/usr/local/lib/R/extra-library:/usr/local/lib/R/site-library
      - RENV_PATHS_ROOT=/usr/local/lib/R/renv-libs
    volumes:
       - /data/shiny-server/apps:/srv/shiny-server/
       - /data/shiny-server/conf:/etc/shiny-server/
       - /data/shiny-server/r-libs:/usr/local/lib/R/extra-library
       - /data/shiny-server/r-libs/renv-libs:/usr/local/lib/R/renv-libs
       - /data/shiny-server/scripts:/scripts
       # Xena data
       - /data/shiny-server/xena:/xena
       # IOBR data
       - /data/shiny-server/iobr-data:/home/shiny/.local/share/R/IOBR
       # Common Research databases
       - /data/shiny-server/databases:/databases
    command: ["/scripts/init.sh", "/init"]
    restart: always